### PR TITLE
Fix errors related to executing dotnet

### PR DESCRIPTION
**Pull request by ywt114**
The problem arises from rm rf/usr/share/dotnet. The solution is to first run apt-get update to update the software package list, and then run apt-get remove - y '^ dotnet -. *' to solve the execution error issue. I have tested and just submitted the issues, but I don't know if they will be killed. You can also fork the project and modify it yourself in the action.yml file by adding a sudo apt-get update before line 174, And there is a duplication between sudo rm - rf/usr/share/dotnet and sudo apt-get remove - y '^ dotnet -. *'. Change to sudo rm - rf/usr/share/dotnet | | true and sudo apt get remove - y '^ dotnet -. *' | | true

### CODE REVIEW

**Comment by normanmaurer** [comment]
Please consider merging this one... Without this PR builds will continue to fail

**Comment by thorstenwagner** [comment]
Workaround: If you set only android to true, it runs.

**Comment by subhamkrai** [comment]
@jlumbroso @gruve-p @rake5k ^^

**Comment by gruve-p** [comment]
> @jlumbroso @gruve-p @rake5k ^^

I am not the maintainer of this repo nor do I have any merge rights, Pinging me will not solve your request.

**Comment by jlumbroso** [comment]
@ywt114 Thanks for your PR! I will merge this, but for future reference, rather than `true`, I prefer a log error message, as @ChrisCarini did very beautifully here:
https://github.com/jlumbroso/free-disk-space/pull/8#pullrequestreview-1580280900

**Comment by ChrisCarini** [comment]
> I prefer a log error message, as @ChrisCarini did very beautifully here:

Thank you for the kind words, @jlumbroso ! 😃

**Pull request merged**
